import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — Nelth-IA',
  description: 'Terms of Service governing the use of Nelth-IA.'
}

const CONTACT_EMAIL = 'optixai32@gmail.com'

export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-3xl px-6 py-12">
      <Link
        href="/"
        className="text-sm text-muted-foreground underline-offset-4 hover:underline"
      >
        ← Back to Nelth-IA
      </Link>
      <h1 className="mt-4 text-3xl font-bold tracking-tight">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Effective date: September 5, 2026
      </p>

      <div className="mt-8 space-y-6 text-sm leading-6 text-foreground/90">
        <section>
          <h2 className="text-lg font-semibold">1. The Service</h2>
          <p className="mt-2">
            Nelth-IA (&quot;the Service&quot;) is an AI-powered answer engine
            that generates responses using third-party AI models. You may
            optionally connect third-party accounts (Google, GitHub, Notion)
            in read-only mode so the assistant can reference your content when
            answering.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">
            2. Accounts and acceptable use
          </h2>
          <ul className="mt-2 list-disc space-y-1 pl-6">
            <li>You must be at least 13 years old to use the Service.</li>
            <li>
              You are responsible for activity under your account and for
              keeping your credentials confidential.
            </li>
            <li>
              You agree not to abuse the Service: no unlawful content, no
              attempts to disrupt, reverse-engineer access controls, or
              circumvent rate limits.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold">
            3. Third-party integrations
          </h2>
          <p className="mt-2">
            Connecting Google, GitHub, or Notion is optional and read-only.
            Those services are governed by their own terms and privacy
            policies. You can disconnect at any time from the connectors panel,
            which deletes the stored OAuth tokens, or by revoking access in
            the provider&apos;s own settings.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">4. AI-generated content</h2>
          <p className="mt-2">
            Responses are generated by AI and may be inaccurate or incomplete.
            They are provided for informational purposes only and do not
            constitute professional advice. Always verify important
            information.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">
            5. Intellectual property
          </h2>
          <p className="mt-2">
            The Service&apos;s code, design, and branding belong to their
            respective owners. You retain all rights to content you provide or
            connect. By using the Service you grant only the limited rights
            needed to operate it (process your queries and display answers).
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">
            6. Disclaimer and limitation of liability
          </h2>
          <p className="mt-2">
            The Service is provided &quot;as is&quot;, without warranties of
            any kind. To the maximum extent permitted by law, the operator is
            not liable for indirect, incidental, or consequential damages
            arising from use of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">7. Termination</h2>
          <p className="mt-2">
            You may stop using the Service at any time. We may suspend or
            terminate access for violations of these terms or to protect the
            Service and its users.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">8. Changes</h2>
          <p className="mt-2">
            These terms may be updated; the effective date above will reflect
            the latest version. Continued use after changes constitutes
            acceptance.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">9. Contact</h2>
          <p className="mt-2">
            Questions about these terms: <strong>{CONTACT_EMAIL}</strong>.
          </p>
        </section>
      </div>
    </main>
  )
}
